### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by Biavleren** [Solvgraa-mager/E4PRJ4#10]
Hvad sker der når du trykket på de enkelte knapper (fx drop-down-menuen) - Billede af det.
En tegneserie af alt hvad der kan ske.

se evt. referat fra d. 24/2.

**Comment by AU636523** [comment]
Screenshots af login, main og kalibreringsunderside med tilhørende billeder af drop downs er tilføjet i rapporten og der er reference til disse relevante steder i krav afsnit .
