### ISSUE TITLE
UC: Initialisering

### ISSUE THREAD

**Issue by AU636523** [Solvgraa-mager/E4PRJ4#12]
Færdig fully dressed UC for UC'en initialisering

**Comment by AdamHoej-au** [comment]
Jeg er lidt i tvivl om hvor ofte UC Initialisering skal køres  - det ligner ud fra UC Tænd, at den køres _hvergang_ systemet er tændes. 

Er det sådan I har tænkt det @Biavleren  og @mrschultzen ? Jeg havde en tanke om at det var en éngangsforestilling og at hvis systemet ved opstart kunne læse en `init.ini` fil eller lign. at den så skippede initialiseringsfasen helt.

**Comment by mrschultzen** [comment]
I princippet havde vi tænkt at køre initialisering hver gang systemet tændes. Vi tænkte ikke det ville være fatalt, men det lider lidt af redundans. Så meget fin tilføjelse du kommer med.
Edit: ændret så der en undtagelse, at hvis der ligger en init.ini fil, så henter den den og undgår at gennemløbe UC Initialisering.

**Comment by ChristianSchultzNielsen** [comment]
Er implementeret i "Tænd" og lukkes
