### ISSUE TITLE
Sensor: Signalbeskrivelse 

### ISSUE THREAD

**Issue by AU636523** [Solvgraa-mager/E4PRJ4#28]

**Comment by AU636523** [comment]
@AdamHoej-au Jeg har tilladt mig at flytte Vandstand-signalet over på ADC blokken for overskuelighedens og strukturens skyld. Så havde jeg tænkt at når man multiplexede over på det signal, var det bare et 2-bits signal man fik ud på ADCData :-) Jeg er helt åben for at flytte den tilbage, hvis du syntes det er underligt..

**Comment by AdamHoej-au** [comment]
Hej Simon! Det ser møg fedt ud det du har haft gang i! 
Jeg er enig med Vandstanden over på ADC'en men arbejde også med nogle tanker inden du flyttede den.
Hvor vi kobler de 3 vandstandssensorere op i et logic system der, hvorved vi har nogle "flag" der kan rejses. 
Jeg kan ikke helt se om er sådan det skulle fungere på længere sigt, men jeg har en idé om at det ville bidrage med noget "sikkerhed" til reguleringen.
![image](https://user-images.githubusercontent.com/56192310/111060192-5cffd700-849b-11eb-8219-ff762a214b03.png)


Desuden undersøgte jeg hvordan vi interfacer de forskellige typer sensorere til ADC'en, og faldt over SDI-12 protokollen som jeg synes vi bør kigge på! 
[SDI-12 Support Group](https://sdi-12.org/)
[Protokol-specifikation](http://www.sdi-12.org/current_specification/SDI-12_version-1_4-Jan-10-2019.pdf)

**Comment by AU636523** [comment]
Vandstandssensor-flag-tankegangen er jeg helt enig i.. Jeg tror det var det vi drøftede - og den skal naturligvis ikke igennem en egentligt ADC. Jeg havde blot en idé om at det ville give mening at den strukturelt gik igennem ADC-blokken, for at alle sensorinput havde samme "kommandovej".. 

Hvis outputtet fra vandstandssensoren er et 4-bit system, som det du har skitseret, så kunne det være sådan at når man multiplexede til vandstand, så stod de 4 bit bare direkte  (uden om en ADC) på udgangen af data :-) 

... Det var bare for at det ville blive en helt skarp strømlinet struktur.. 

Og fedt at det ser ud til at du allerede har fået lavet et setup på hvordan det bliver konverteret fra vandstand til bits 👍
