### ISSUE TITLE
Revurdering af UseCase "Regulér" og "Tænd"

### ISSUE THREAD

**Issue by Biavleren** [Solvgraa-mager/E4PRJ4#36]
De 10 usecases er blevet kogt ned til 7.
Regulér og tænd skal omskrives

**Comment by ChristianSchultzNielsen** [comment]
Reguler og tænd  er skrevet om, samt orden på alle use cases opdateret.

Skrevet mail til John og venter svar.

**Comment by ChristianSchultzNielsen** [comment]
Afventer møde mandag kl. 14

**Comment by ChristianSchultzNielsen** [comment]
Punkter til spørgsmål fra sekvensdiagrammer:
- Skal systemet indlæse network-settings under use case "tænd"? (Den er taget med i sekvens og use case so far..)
- Ønsker John en runWizard() - sekvensdiagram? Eller går læser op og kigger i use case?

**Comment by ChristianSchultzNielsen** [comment]
.
