### ISSUE TITLE
Use Case udkast

### ISSUE THREAD

**Issue by ChristianSchultzNielsen** [Solvgraa-mager/E4PRJ4#5]
- [x] Udkast for forskellige use cases
- [x] Skriv udkast til hver use case
- [ ] Skriv om færdigt udkast til gruppen på messenger
- [ ] Evaluering af use cases fra udkast
- [ ] Evt. flere use cases og udarbejdning af disse
- [ ] Evaluering af eventuelle use cases
- [ ] Klar inden møde

**Comment by AdamHoej-au** [comment]
Jeg har tilføjet 2 use case udkast til overleafprojektet.
- Førstegangs opsætning af systemet
- Indstilling af reguleringsmuligheder.

**Comment by ChristianSchultzNielsen** [comment]
Use case udkastet er done
